networks:
  app_network:

services:
  database:
    image: ghcr.io/onixbyte-business/score-sense/score-sense-db:${APP_VERSION:-latest}
    ports:
      - "${DB_PORT:-55432}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-123456}
    networks:
      - app_network
  
  server:
    depends_on:
      - database
    image: ghcr.io/onixbyte-business/score-sense/score-sense-server:${APP_VERSION:-latest}
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      ACTIVE_PROFILES: ${ACTIVE_PROFILES:-prod,wechat,db}
    volumes:
      - ${SERVER_CONFIG_PATH:-./config}:/app/config
    networks:
      - app_network

    